### PR TITLE
NumberPicker: add option of vibration on value change

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] https://github.com/Samsung/TAU/issues/1534
[Problem] NumberPicker: add option of vibration on value change
[Solution]
 - new option has been added

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Review by HunseopJeong — APPROVED** [review]
LGTM

**Comment by TomaszLukawskiSam** [comment]
> LGTM

Thank You for review.
I updated PR because of merge conflict and I changed property for vibration triggering. The `_count` is better then `value` because the `value` can be changed with floating step eg. `0.5`.

**Review by DohyungLim — APPROVED** [review]
LGTM

**Review by lbardeli — APPROVED** [review]
LGTM

**Review by singa2000 — APPROVED** [review]
Good

**Pull request merged**
