### PR TITLE
Group Index Center (Wearable): examples and style update

### PR DESCRIPTION
**Pull request by grzegorz-czajkowski**
[Issue] https://github.com/Samsung/TAU/issues/1060
[Problem] Missing example and out dated styles
[Solution] Update style add examples.
	This PR partially reverts https://github.com/Samsung/TAU/pull/947
	since there is mistake in guide (#artboard40 does not show
	group index but rather Tile Bar with Subtitle).

Signed-off-by: Grzegorz Czajkowski <g.czajkowski@samsung.com>

### CODE REVIEW

**Comment by grzegorz-czajkowski** [comment]
Arclistview displays 3 items by default including group indexes. Because of that, examples look different according to guide (there are visible 3 items + 2 group indexes). This requires changes in Arclistview.js

**Review by korneliakobiela — APPROVED** [review]
LGTM :+1:

**Comment by grzegorz-czajkowski** [comment]
Created issue for Arclistview https://github.com/Samsung/TAU/issues/1166

**Comment by grzegorz-czajkowski** [comment]
Just replaced spaces with tabs in alistview.less. No logic changes.

**Pull request merged**
