### PR TITLE
(HomeTV App) Payment demo page

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] https://github.com/Samsung/TAU/issues/1347
[Problem] Add payment page on submit your order
[Solution]
 - new page has been added

[Screenshot]
obraz

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Comment by singa2000** [comment]
For  payment demo page, would you add the followings please?
"Card Number"
[Input number field]
"Expiry Date"
[Input number field]
"CVC Number]
[Input number field]

Or it's enough to link the payment site..

**Comment by TomaszLukawskiSam** [comment]
> For payment demo page, would you add the followings please?
> "Card Number"
> [Input number field]
> "Expiry Date"
> [Input number field]
> "CVC Number]
> [Input number field]
> 
> Or it's enough to link the payment site..

I can add such fields, but it seems more recent that the card information is already entered into the system. Users can choose whether to pay by card or add to the room bill.

eg.

(O) pay with MC **** - 5566 card
(  ) Add to the room bill

What do you think?

**Comment by singa2000** [comment]
@TomaszLukawskiSam 
Ok. Your suggestion looks good.
What I wanted, it was a scenario that actually seemed to be paid.

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam
> Ok. Your suggestion looks good.
> What I wanted, it was a scenario that actually seemed to be paid.

Maybe add one more subpage at the end of the payment?

obraz

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam
> Ok. Your suggestion looks good.
> What I wanted, it was a scenario that actually seemed to be paid.

and can add payment process

obraz

**Comment by singa2000** [comment]
@TomaszLukawskiSam 
and can add payment process
--> It's not needed in now. Thanks.^^

**Pull request closed without merging**
