### PR TITLE
Set sonarlint rules as TAU workspace specific

### PR DESCRIPTION
**Pull request by lslachciak**
[Issue] https://github.com/Samsung/TAU/issues/1068
[Problem] VSCode not having SonarLint rules configuration
[Solution] Add workspace specific setting

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Comment by TomaszLukawskiSam** [comment]
This works on my local VSCode but user has to open TAU project as workspace.
We can append workspace file to repository, eg. tau.code-workspace:
```
{
	"folders": [
		{
			"path": "."
		}
	]
}
```

**Comment by TomaszLukawskiSam** [comment]
I verified again this patch... and I have to change opinion. I doesn't work on my VSCode.
obraz

I added rule "S3513" and check in Sonarllint plugin - the rule remains "off".

**Review by DohyungLim — COMMENTED** [review]
If there are no problems, how about organizing the PR?

**Comment by lslachciak** [comment]
I'm closing this PR, we will open new one when have working solution

**Pull request closed without merging**
