### PR TITLE
Sync jQuery library version

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] N/A
[Problem] jQuery version is different between uncompressed and minified
[Solution] Update uncompressed jQuery version to the 2.1.1

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Review by TomaszLukawskiSam — COMMENTED** [review]
This change looks good to me, but it can have impact on apps which use jquery from TAU

**Comment by singa2000** [comment]
It's the PR for fixing  jQuery version is different between uncompressed and minified.
I think we have to make same version uncompressed and minified.
If the PR merge,  is there any problem with TAU working?
If there is no problem, how about to merge it?

**Review by lslachciak — APPROVED** [review]
OK I think this should have no influence on TAU

**Review by TomaszLukawskiSam — APPROVED** [review]
looks good to me.

**Pull request merged**
