### PR TITLE
TextInput (wearable): Input element is broken with number type

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] https://github.com/Samsung/TAU/issues/971
[Problem] The number type of the input element is not working correctly
[Solution] Add a number type to the styles and add a condition to check
whether input element supports the selectionStart property

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
I think this PR needs to be applied from 1.0 to 1.2.

**Review by lslachciak — COMMENTED** [review]
Could you also update example
https://github.com/Samsung/TAU/blob/tau_1.0/examples/wearable/UIComponents/contents/controls/text-input.html
so we can show that we support also number type
e.g. instead of phone number we can set year of birth

And I agree this change should be applied to all branches

**Comment by HunseopJeong** [comment]
@lslachciak,
Yes, you are right. I also updated the example.
Done.

**Review by lslachciak — APPROVED** [review]
works well. can be merged

**Review by singa2000 — APPROVED** [review]
It looks good.

**Pull request merged**
