### PR TITLE
TAU 1.2.5 release

### PR DESCRIPTION
**Pull request by lslachciak**
Dedicated platform: Tizen 6.0

New features in 1.2.0:
 - support for OneUI 2.x

Changes in version 1.2.5:

e6d86f0 (mobile) OnOffSwitch: set constant width and height
051c51e Remove additional effect
dafe74f Fixed paddings and bottom margin of toast message
bf53dd5 Fix toasts fonts
28b4fdb Spin: fix for stop scroll on swipe
d124b35 Fix toast colors
7fd7f46 Add theme changing option to the main menu
af7ab8d Proper shape for toast message
2c7cdb9 Spin: fix for scroll stop on drag
0cf6a69 (examples) ScheduleApp: fix for back button on the Add schedule page
7c36a13 (mobile) DropDownMenu: fix for wrong padding and wrong top margin
a74c56c Add support for HW back button
97dc155 (examples) ScheduleApp: add default activities
ad83eed Group Index Left (Wearable): add examples and style
6b96bb9 (tau_1.2, gh-pages) Remove the focus box after clicking the button
cfbcdf3 (mobile) DateTimePicker: widget implementation
3eba50a (mobile) DateTimePicker rename to DateTimePickerWheel
51dc382 (mobile) TimePicker, DataTimePicker: fix for inactive input bg color
b145968 (mobile) Updated images according to the GUI Guide 2.2
bfbb7ef Update .gitignore files to ignore release/debug files
2f8bb77 Group Index Content Page (Wearable): add example and style
6d30852 Spin: implement carousel for performance improvement
8e94a26 Group Index Center (Wearable): examples and style update
8ed354c Creating new schedule dynamically
6abcfca Adjust ScheduleApp example.
ea8ea3a Add simple ScheduleApp project from Android Studio wizard
f47ed0c List Divider Simple (example): use ui-listview
eac28c4 List Divider Simple (Wearable): update style according to guideline
0e46520 Add a about page on the UIComponent
23107fa Adjust Empty app to UIComponents example
bb2cbd9 Add empty Android Studio project for UIComponents app
b38d397 (example) ScheduleApp: save data from create event form
e51389f List Divider (Multiline): add examples and styles
9beb596 Fix background on dialog element in dark mode
91544c6 Implement changing theme feature using Dropdown menu
fb5685d BottomBar: fix for text verical align in anchor based button
1d43317 OnOffSwitch: fix for broken look after re-open page
5bea8b0 DayOfWeekPicker: fix for button of days look wrong after reopen page
c5869b4 (example) ScheduleApp: schedule list after event create
a745b9d (mobile) ScheduleApp: Change DatePicker to Calendar on date click
2a8b8b0 (mobile) Calendar: padding added to calendar in content are
f1abb60 Enable the Dialog and View-Controls
b68a0c3 Re-enable picker dialogs link
57dc108 Add proper margins to Content Subheader element
9fb3e83 Create Day of the week indicator
bfadf3b (core) Spin and Appbar: lockExpanding on Spin drag
24463fa List: Sub Text Max Text (Wearable): add example and style
9bc7d05 (core) Spin: lock scroll before drag event on widget
59f2d03 (example) DayOfWeekPicker: new widget and example
7931883 example: update Icon Left/Right (Wearable)
64fc2e4 (mobile) Page: bottom round corner for content
aebd76a Implement static elements for the webpage
0260929 DateTimePicker: widget implementation and sample
a9f26cc Remove the svg file from the mask-border
4af1df7 List: Icon Left/Right (Wearable): add example and style

### CODE REVIEW

**Review by TomaszLukawskiSam — COMMENTED** [review]
Remove (HEAD, origin/tau_1.2)

**Review by TomaszLukawskiSam — COMMENTED** [review]
remove (tau_1.2, gh-pages)

**Comment by korneliakobiela** [comment]
Hmm, shouldn't we make npm install to update package-lock.json?

**Review by korneliakobiela — COMMENTED** [review]
Shouldn't we make npm install to update package-lock.json?

**Comment by grzegorz-czajkowski** [comment]
Did verification of wearable profile and found the following issues: https://github.com/Samsung/TAU/issues/1214, https://github.com/Samsung/TAU/issues/1213, https://github.com/Samsung/TAU/issues/1212, https://github.com/Samsung/TAU/issues/1211.

**Comment by lslachciak** [comment]
> 
> 
> Shouldn't we make npm install to update package-lock.json?

I made npm install and didn't observe any changes in package-lock.json

**Comment by lslachciak** [comment]
> Remove (HEAD, origin/tau_1.2)
>remove (tau_1.2, gh-pages)

done

**Review by korneliakobiela — APPROVED** [review]
LGTM

**Pull request merged**
