### PR TITLE
Display the initial state of radio checkbox

### PR DESCRIPTION
**Pull request by hsiwkin**
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/126
[Problem] "The Active Radio" text wasn't initially set to the selected value
[Solution] Check which option is selected and update the text with it's value

Signed-off-by: Hubert Siwkin <h.siwkin@samsung.com>

### CODE REVIEW

**Review by TomaszLukawskiSam — CHANGES_REQUESTED** [review]
This pull request should be addressed to TAU_1.0 branch.

**Review by TomaszLukawskiSam — APPROVED** [review]
false

**Review by TomaszLukawskiSam — CHANGES_REQUESTED** [review]
Issue still exists.

**Comment by hsiwkin** [comment]
I've created another commit with TAU_1.0 branch as the merge target.

**Pull request closed without merging**
