### PR TITLE
[mobile] Remove unneeded sliding effect

### PR DESCRIPTION
**Pull request by lslachciak**
Remove unneded sliding effect

[Issue] #741
[Problem] Sliding effect not specified in guide
[Solution] Remove unneeded effect

### CODE REVIEW

**Comment by lslachciak** [comment]
patch rebased, please review

**Review by HunseopJeong — APPROVED** [review]
LGTM

**Comment by lslachciak** [comment]
Resend patch to force CI start checking it, looks like there are some CI problems today

**Comment by HunseopJeong** [comment]
> 
> 
> Resend patch to force CI start checking it, looks like there are some CI problems today

Yes.. I am waiting for finishing the check.

**Comment by lslachciak** [comment]
resend again

**Pull request merged**
