### PR TITLE
Change bundled libraries filenames

### PR DESCRIPTION
**Pull request by pkaczmarczy**
[Issue] https://github.com/Samsung/TAU/issues/358
[Problem] Bundled external libraries location and
          filenames might not be clear for developers
[Solution] Change filenames and location for bundled
           third party libraries

Signed-off-by: Pawel Kaczmarczyk <p.kaczmarczy@samsung.com>

### CODE REVIEW

**Review by TomaszLukawskiSam — APPROVED** [review]
Looks good to me.

**Comment by pkaczmarczy** [comment]
Dear @TomaszLukawskiSam , I have updated the PR, Could you take a look at it again?

**Comment by lslachciak** [comment]
@pkaczmarczy can we merge this item?

**Comment by pkaczmarczy** [comment]
I'd rather wait for latest commits approve (there are three new commits).

**Comment by lslachciak** [comment]
Ok, @TomaszLukawskiSam  could you re-approve?

**Review by TomaszLukawskiSam — APPROVED** [review]
Verified. Looks good to me.

**Pull request merged**
