### PR TITLE
Update set of resources for mobile profile v1.6_200317

### PR DESCRIPTION
**Pull request by lslachciak**
[Issue] https://github.com/Samsung/TAU/issues/776
[Problem] Not up to date resources
[Solution] Update resources with version v1.6_200317

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Comment by lslachciak** [comment]
I didn't delete  src/css/profile/mobile/theme-changeable/images/0_Round_corner/round.svg
even if it not exist in latest version of components to avoid breaking ui-content
Please note that I created also issue https://github.com/Samsung/TAU/issues/778 for this

**Review by TomaszLukawskiSam — APPROVED** [review]
Looks good to me.

**Review by grzegorz-czajkowski — APPROVED** [review]
Let's merge it so I could update icons dropdown patch.

**Comment by lslachciak** [comment]
Please note that also issues are created:
https://github.com/Samsung/TAU/issues/780
https://github.com/Samsung/TAU/issues/779

**Pull request merged**
