### PR TITLE
Fix gridview image in the TV resolution

### PR DESCRIPTION
**Pull request by singa2000**
[Problem] The gridview is not fit in the TV resolution
[Solution]
Modify the gridview width, height

Signed-off-by: singa2000 <cookie@samsung.com>

### CODE REVIEW

**Comment by singa2000** [comment]
In case of TV resolution, the image of grid is not fit.

**Comment by singa2000** [comment]
Screenshot from 2021-10-08 15-52-41

**Comment by singa2000** [comment]
Screenshot from 2021-10-08 15-58-07

**Review by TomaszLukawskiSam — APPROVED** [review]
Verified. The PR looks good to me.

**Comment by TomaszLukawskiSam** [comment]
Dear @singa2000 , you have to rebase your PR to resolve CI issue.

**Comment by TomaszLukawskiSam** [comment]
> Screenshot from 2021-10-08 15-58-07

I prepared PR (https://github.com/Samsung/TAU/pull/1692) for this issue. Could you check this PR? Thank you.

**Pull request merged**
