### PR TITLE
Update move and add button image

### PR DESCRIPTION
**Pull request by singa2000**
[Issue] https://github.com/Samsung/TAU/issues/884
[Problem] Move and Add button image are wrong
[Solution] Update the button image

Signed-off-by: cookie <cookie@samsung.com>

### CODE REVIEW

**Review by lslachciak — COMMENTED** [review]
please link to this issue 
https://github.com/Samsung/TAU/issues/884
in commit message
In which situation add button is not visible?

**Comment by singa2000** [comment]
It's right the issue https://github.com/Samsung/TAU/issues/884.
- Move button
List -> Multiple Selection List -> Select items : the move icon is not display.
- Add button
List ->End of list -> Bottom spacing with FAB

**Review by lslachciak — APPROVED** [review]
works well

**Review by HunseopJeong — APPROVED** [review]
LGTM

**Pull request merged**
