### PR TITLE
NumberPicker: implementation of carousel (work in progress)

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] N/A
[Problem]
[Solution]

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Comment by lslachciak** [comment]
let's consider this for wearable 1.2

**Review by DohyungLim — COMMENTED** [review]
@TomaszLukawskiSam 

I have a question.
For NunberPicker, is it possible to recycle code on mobile?

**Comment by TomaszLukawskiSam** [comment]
I’m not sure at the moment.

I didn’t check differences.

 

Tomasz

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam
> 
> I have a question.
> For NunberPicker, is it possible to recycle code on mobile?

I’m not sure at the moment.
I didn’t check differences.

**Comment by TomaszLukawskiSam** [comment]
I close this PR now. We can restore it in future.

**Pull request closed without merging**
