### PR TITLE
Creating app with two empty pages

### PR DESCRIPTION
**Pull request by korneliakobiela**
[Issue] #1079
[Problem] Sample scheduling app wasn't exist.
[Solution]
- Create app template
- Create HTML for two pages
- Linking TAU library

Signed-off-by: Kornelia Kobiela <korneliak.95@gmail.com>

### CODE REVIEW

**Review by HunseopJeong — APPROVED** [review]
LGTM

**Review by DohyungLim — APPROVED** [review]
lgtm.

**Review by lslachciak — COMMENTED** [review]
Could you also add Tizen Project (as in case of other examples) file to this sample app so we can easily run it on emulator?

**Review by lslachciak — APPROVED** [review]

**Comment by korneliakobiela** [comment]
Can I do it with next PR about dialog?

**Comment by lslachciak** [comment]
sure

**Pull request merged**
