### PR TITLE
Add travis configuration support

### PR DESCRIPTION
**Pull request by lslachciak**
[Issue] N/A
[Problem] Upload of PR takes long time
[Solution] Use online travis for tests

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
Do we need to add the command for the test? replace with 'npm install && npm test'?

**Comment by lslachciak** [comment]
npm install and npm test is invoked by default for 
language: node_js configuration
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by lslachciak** [comment]
See also https://github.com/Samsung/WATT/blob/master/.travis.yml
it doesn't have npm test but test are invoked

**Comment by HunseopJeong** [comment]
Oh,, You are right, It looks like working by default.
I enable the travis for the TAU and the TAU-DE.
You can test the travis.

**Comment by lslachciak** [comment]
Travis CI passes too: https://travis-ci.org/Samsung/TAU/builds/529170868?utm_source=github_status&utm_medium=notification

**Comment by HunseopJeong** [comment]
It looks working good :)

**Pull request merged**
