### PR TITLE
(mobile) ToggleSwitch: fix for conflict data-style and style attribute

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] N/A
[Problem] ToggleSlider: Widget looks like standard toggleswitch after any style change
[Solution] Name of widget option "data-style" has changed to "data-appearance".

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Comment by singa2000** [comment]
@TomaszLukawskiSam 
I have a question.
Is it just for mobile profile?
In the Design Editor for Wearable, there is also ToggleSlider widget.
How about the  wearable profile?

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam
> I have a question.
> Is it just for mobile profile?
> In the Design Editor for Wearable, there is also ToggleSlider widget.
> How about the wearable profile?

This patch is only for mobile profile. I thought that this is clue of issue.

In werable profile, in latest UX 2019 toggleswitch has changed look.
I have to check current state an in my opinion we have to change this.
image

Current toggleswitch.
image

**Comment by TomaszLukawskiSam** [comment]
> > @TomaszLukawskiSam
> > I have a question.
> > Is it just for mobile profile?
> > In the Design Editor for Wearable, there is also ToggleSlider widget.
> > How about the wearable profile?
> 
> This patch is only for mobile profile. I thought that this is clue of issue.
> 
> In werable profile, in latest UX 2019 toggleswitch has changed look.
> I have to check current state an in my opinion we have to change this.
> image
> 
> Current toggleswitch.
> image

At the moment we have implemented both form.
image

I'll check this in design editor.

**Comment by TomaszLukawskiSam** [comment]
In Design Editor in wearable profile the issue are still occurring.
But this solving this issue is more complicated. I'll create issue for wearable profile.

image

**Comment by TomaszLukawskiSam** [comment]
New issue:
https://github.com/Samsung/TAU-Design-Editor/issues/79

**Comment by TomaszLukawskiSam** [comment]
> Please change the data property in UIComponents mobile sample
Done :)

**Pull request merged**
