### PR TITLE
(example) UIComponents: Service Card example

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] https://github.com/Samsung/TAU/issues/1388
[Problem] New WebClip template: Service
[Solution]
 - new examples has been added

[Known issues]
- Tabs: https://github.com/Samsung/TAU/issues/1401
- List: https://github.com/Samsung/TAU/issues/1402
- Wrong more button https://github.com/Samsung/TAU/issues/1403
- Labels https://github.com/Samsung/TAU/issues/1404

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Comment by lslachciak** [comment]
great!
with this PR I was able to load external webclip in HomeApp
`card.setAttribute("data-src", "http://106.120.63.110:8080/examples/mobile/UIComponents/webclip/link-container/webclip.html");`


All resources loaded correctly except one image, but this looks like a problem of example
`localhost:3000/webclip/restaurant/images/800px-Korean.cuisine-Bibimbap-01.jpg:1 GET http://localhost:3000/webclip/restaurant/images/800px-Korean.cuisine-Bibimbap-01.jpg net::ERR_CONNECTION_REFUSED`

image

**Comment by singa2000** [comment]
Thanks for your checking.
I have one question about the external webclip.
If there is javascript file  like the http://106.120.63.110:8080/examples/mobile/UIComponents/webclip/link-container/aaa.js, is it good working?
If the webclip.html file include the local .js file or external .js file, is it no problem?

**Comment by singa2000** [comment]
F.Y.I
"Link Card" naming is change to "Service Card" in the "0904 UI Guide".
The content type is "Tab", "Container","Video","Icon","List","Thumbnail list".

**Comment by singa2000** [comment]
Would you check the followings travis-ci erro, please?
/home/travis/build/Samsung/TAU/src/js/core/widget/core/Card.js
  49:5  error  'pathUtils' is assigned a value but never used  no-unused-vars

**Comment by TomaszLukawskiSam** [comment]
> Would you check the followings travis-ci erro, please?
> /home/travis/build/Samsung/TAU/src/js/core/widget/core/Card.js
> 49:5 error 'pathUtils' is assigned a value but never used no-unused-vars

Done.

**Comment by lslachciak** [comment]
> 
> 
> Thanks for your checking.
> I have one question about the external webclip.
> If there is javascript file like the http://106.120.63.110:8080/examples/mobile/UIComponents/webclip/link-container/aaa.js, is it good working?
> If the webclip.html file include the local .js file or external .js file, is it no problem?


@singa2000 I made a check.
In webclip.html I included some simple script which was producing some output
 <script src="script.js"></script>
script.js was located in webclip directory. It executed successfully.
also when referencing to external resource for webclip
<script src="http://106.120.63.110:3000/js/srcipt.js"></script>

**Comment by TomaszLukawskiSam** [comment]
> great!
> with this PR I was able to load external webclip in HomeApp
> `card.setAttribute("data-src", "http://106.120.63.110:8080/examples/mobile/UIComponents/webclip/link-container/webclip.html");`
> 
> All resources loaded correctly except one image, but this looks like a problem of example
> `localhost:3000/webclip/restaurant/images/800px-Korean.cuisine-Bibimbap-01.jpg:1 GET http://localhost:3000/webclip/restaurant/images/800px-Korean.cuisine-Bibimbap-01.jpg net::ERR_CONNECTION_REFUSED`
> 
> image

Yes. It was sample for test. I removed this.

**Review by singa2000 — APPROVED** [review]
Now it looks good to me.
If there is more update, it will be next PR.

**Review by lslachciak — APPROVED** [review]

**Pull request merged**
