### PR TITLE
(tests) Fix for test of util/polar

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] N/A
[Problem] Util/polar test fails on latest browser
[Solution] Web browser behaviour has been changed for
 transformOrigin style and test fails

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Review by HunseopJeong — APPROVED** [review]
LGTM

**Review by DohyungLim — APPROVED** [review]
looks good.

**Review by lslachciak — APPROVED** [review]
change seems ok, but I have one doubt, this test is executed only for mobile in case of phantom based test execution
https://travis-ci.org/github/Samsung/TAU/builds/677268976
do you know why it is not considered for wearable?

**Comment by singa2000** [comment]
In case of tct, we have just mobile TCT.
Wearable don't have the TCT.

I have a question,
It it also apply in the tau_1.1 branch?

**Comment by lslachciak** [comment]
@singa2000 I don't have concern regarding TCT but test executed on CI.
I think this change is also applicable to other branches too.

**Comment by TomaszLukawskiSam** [comment]
> I have a question,
> It it also apply in the tau_1.1 branch?

I think this patch can be partially applied to tau_1.1 / tau_1.0 branch. We can copy there the fix for test.
but
we don't need change refers to karma test. Karma tests are implemented only on 1.2 branch.

**Pull request merged**
