### PR TITLE
List (mobile): Update the UX of the List

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] N/A
[Problme] Need to update the UX for List
[Solution] Apply 5.3 and 6.8

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
Snapshot
divider for on off switch
image

Expandable list
image

**Review by TomaszLukawskiSam — APPROVED** [review]
Verified. Looks good to me.

**Comment by TomaszLukawskiSam** [comment]
@HunseopJeong 
Hi, after your list updates, many list has wrong look. 
image

Do you have a plan for remain some backward compatibility?

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
Okay I will check it.

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam @lslachciak.
Could you merge this PR, I will upload the new PR to apply changed listview UX.

**Comment by lslachciak** [comment]
done

**Pull request merged**
