### PR TITLE
Fix a problem that opacity is not applied on emulator

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] N/A
[Problem] Opacity effect is not applied when using the percent
[Solution] Change the opacity value to use the floating value

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Review by TomaszLukawskiSam — APPROVED** [review]
Looks good to me.

**Review by singa2000 — APPROVED** [review]
It's good working

**Comment by TomaszLukawskiSam** [comment]
@HunseopJeong 
Hi,
This problem intrigued me and I found convertion method in `less` http://lesscss.org/functions/#misc-functions-unit
eg. `--opacity: unit(10%) / 100`
This allows to remains the same format of write a values for opacity

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
Oh I see,, I will create the issue for this problem.
Thank you.

**Pull request merged**
