### PR TITLE
Fix problem that scrollToPosition is not working correctly

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] N/A
[Problem] SnapListview.scrollToPosition is not working
[Solution] Sync the index and position with scroller
and calculate the rendered position with the scrolled
value and add the 'skipAnimation' to skip the animation

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Review by TomaszLukawskiSam — COMMENTED** [review]
I'm reviewing this PR at the moment.

**Review by TomaszLukawskiSam — COMMENTED** [review]
Works better but some issues still exists.
image

These issue can be reproduce by scroll by touch and call method scrollToPosition(n)

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
I checked issue and fixed it.
Could you re-check the issue on your reproduced steps?

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam,
> I checked issue and fixed it.
> Could you re-check the issue on your reproduced steps?

I verified again. The issue doesn't occur anymore.
Now I'll check on device in Sample app.

**Review by TomaszLukawskiSam — APPROVED** [review]
I verified PR on device in sample app. Works fine.

**Pull request merged**
