### PR TITLE
Add bundled file containing all external libraries and base TAU

### PR DESCRIPTION
**Pull request by pkaczmarczy**
[Issue] https://github.com/Samsung/TAU-Design-Editor/issues/388
[Problem] Such a file is required to keep
          backward compability in Design Editor
[Solution] Add Grunt task

Signed-off-by: Pawel Kaczmarczyk <p.kaczmarczy@samsung.com>

### CODE REVIEW

**Comment by pkaczmarczy** [comment]
Verification in progress.

I have checked mobile profile samples with fresh tau.bundle file only included - It looks like they are OK

**Review by DohyungLim — APPROVED** [review]
I tested all the i3d, coverflow and graph widgets.
All work fine in the wearable profile DE.

**Comment by lslachciak** [comment]
I think this PR may be used for providing samples app for testing
But before merging this we need to make sure that this is best option

**Comment by pkaczmarczy** [comment]
@lslachciak I think this PR is no longer needed. Can we close it?

**Comment by lslachciak** [comment]
yes, currently not needed
alternative solution was chosen

**Comment by pkaczmarczy** [comment]
The PR is no longer needed.

**Pull request closed without merging**
