### PR TITLE
Spin: Reduce the number of function calls by drag

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] N/A
[Problem] Sometimes causes excessive value changes when dragging a spin
[Solution] Increase the threshold for changing the value

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Review by TomaszLukawskiSam — APPROVED** [review]
Looks good to me.

**Comment by TomaszLukawskiSam** [comment]
@HunseopJeong 
Hi, you can merge this PR.

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam 
I will check it with @singa2000 and then merge it.

**Review by singa2000 — APPROVED** [review]
Looks good.

**Pull request merged**
