### PR TITLE
(example) HomeApp: change emebeded content of widget to iframe

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] https://github.com/Samsung/TAU/issues/1360
[Problem] Confirm that widgets can be loaded using iframes
[Solution]
 - Hotel Breakfast content has been changed to iframe

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Comment by singa2000** [comment]
There is not needed the wearable library.
I think it's enough the mobile library.
Would you remove it, please?

**Comment by singa2000** [comment]
If each web clip have the own tau library, the size is too big.
HomeApp should be light and fast.
I think we need to get the solution for it.
(Maybe developer will release the their web clip with tau library)

**Comment by lslachciak** [comment]
> If each web clip have the own tau library, the size is too big.

Yes, this is one of the biggest drawbacks of the iframe approach. We are aware of it.
In case of few webclips this will mean that TAU library is loaded to memory few times.
We are thinking if there is a better approach

**Comment by lslachciak** [comment]
One of another issues which I see here is size of widgets. They don't fit in app correctly. 
@TomaszLukawskiSam I uderstand this is a problem of iframe which can not set content size?
image

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
The iframe solution causes a lot of problems: repeatedly embedded TAUs, problems with widget dimensions, problems with graphic themes.

Currently I am preparing a solution based on Custom Elements. There are also problems but different. Mainly a problem with relative url for images https://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0013.html

**Comment by TomaszLukawskiSam** [comment]
This PR is deprecated.

**Pull request closed without merging**
