### PR TITLE
Delete unnecessary sample files

### PR DESCRIPTION
**Pull request by singa2000**
[Issue] N/A
[Problem] There is unnecessary sample files
[Solution] Delete unnecessary sample files

Signed-off-by: cookie <cookie@samsung.com>

### CODE REVIEW

**Review by DohyungLim — COMMENTED** [review]
I just want to change the spelling of the title.

**Comment by singa2000** [comment]
@DohyungLim 
OK. How do you want to change the spelling?

**Comment by DohyungLim** [comment]
unnecessay -> unnecessary

**Review by TomaszLukawskiSam — APPROVED** [review]
Looks good to me. We can remove these examples from the application.

**Pull request merged**
