### PR TITLE
Rename files with kebab case style

### PR DESCRIPTION
**Pull request by HunseopJeong**
[Issue] #802
[Problem] Several naming rules are used irregularly
[Solution] Rename files with kebab case style

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
It is hard to judge which of 'searchbar' and 'search-bar' is correct.
So I just change the camel and the snake cases to the kebab case.

**Review by TomaszLukawskiSam — APPROVED** [review]
Looks good to me.

**Review by DohyungLim — APPROVED** [review]
LGTM.

**Review by DohyungLim — COMMENTED** [review]
you need to check conflict branch.

**Review by lslachciak — APPROVED** [review]
for wearable profile I think we will need unificaiton too

**Comment by HunseopJeong** [comment]
> 
> 
> for wearable profile I think we will need unificaiton too

Good Think :D We would be good to apply same rules!

**Review by singa2000 — APPROVED** [review]
It's good.
I will follow the coding rule.

**Pull request merged**
