### PR TITLE
[wearable] Move unneeded items to Etc

### PR DESCRIPTION
**Pull request by lslachciak**
[Issue] https://github.com/Samsung/TAU/issues/938
[Problem] Items not present in guide are available in main menu
[Solution] Move items to Etc. Update paths.

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Review by grzegorz-czajkowski — APPROVED** [review]
Woks fine. During verification I notice that Circular SectionChanger works in the same way as horizontal one. Could you check this on your side as well?

**Review by hs85jeong — APPROVED** [review]
I know it's moving files, but it would be nice to change the file name to kebab style while doing the moving. It is not an important issue.

**Comment by lslachciak** [comment]
> 
> 
> I know it's moving files, but it would be nice to change the file name to kebab style while doing the moving. It is not an important issue.

We need to change this globally so I propose to do this in separate issue
https://github.com/Samsung/TAU/issues/940

**Comment by lslachciak** [comment]
> Woks fine. During verification I notice that Circular SectionChanger works in the same way as horizontal one. Could you check this on your side as well?

@lslachciak I will verify examples separately

**Comment by lslachciak** [comment]
@grzegorz-czajkowski circular and horizotal section changer looks the same, but they works in different way. From the last section you can go to the first one in case of circular. In case of horizontal you just have edge effect. Verified on latest HEAD (including this PR)

**Comment by lslachciak** [comment]
image

**Comment by lslachciak** [comment]
image

**Comment by grzegorz-czajkowski** [comment]
@lslachciak I missed this. Thanks for check and explanation.

**Pull request merged**
