### PR TITLE
SVACE rules for local SonarLint VSC extension

### PR DESCRIPTION
**Pull request by TomaszLukawskiSam**
[Issue] https://github.com/Samsung/TAU/issues/1068
[Problem] We cannot check SVACE issues localy
[Solution]
 Added SVACE rules to repository. Now, developer has tools
 to local verification of code.

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

### CODE REVIEW

**Review by lslachciak — CHANGES_REQUESTED** [review]
I thing we should prepare config  file for the workspace not for user
If you go to the plugin configuration and click on the worksapce tab --> Edit in settings.json
new file will be create under
src/.vscode/settings.json
(if you started vscode with src folder)

**Comment by TomaszLukawskiSam** [comment]
> I thing we should prepare config file for the workspace not for user
> If you go to the plugin configuration and click on the worksapce tab --> Edit in settings.json
> new file will be create under
> src/.vscode/settings.json
> (if you started vscode with src folder)

Thank you :) . I'll change this.

**Comment by TomaszLukawskiSam** [comment]
> > I thing we should prepare config file for the workspace not for user
> > If you go to the plugin configuration and click on the worksapce tab --> Edit in settings.json
> > new file will be create under
> > src/.vscode/settings.json
> > (if you started vscode with src folder)
> 
> Thank you :) . I'll change this.

I tried to do it refer to your suggestion but it doesn't work on my VSC

**Review by lslachciak — APPROVED** [review]
Let's merge this file now and improve file location later

**Review by lslachciak — APPROVED** [review]

**Comment by singa2000** [comment]
In the our system also have the checking the SVACE in the each PR.
I'll check it it's possible also in the public github,

**Comment by singa2000** [comment]
It's not support the SVACE checking system in the public github.
We need the this PR.

**Pull request merged**
